# config file for the job execution on cluster 

__default__:
    account: "ClinicalMicrobio"
    cpus-per-task: 1
    time: "12:00:00"
    mem: 32768
    output: "logs/{rule}-%j.out"
    #output: "logs/{rule}.out"
    error: "logs/{rule}-%j.err"
    #error: "logs/{rule}.err"

main:
    time: "02:00:00"
    mem: 16384

trim_reads:
    cpus-per-task: 8

flye_vanilla:
    mem: 32768
    cpus-per-task: 16
flye_size:
    mem: 32768
    cpus-per-task: 16
flye_meta:
    mem: 32768
    cpus-per-task: 16


kraken2:
    mem: 65536
    cpus-per-task: 4


snippyself:
    cpus-per-task: 4



